Fix broken finalisation routine for Blender 2.90
animate1978/MB-Lab pull request #300
Opened 2020-09-07 02:12 UTC by calben

Some modifiers were previously applied as data.
I'm not sure why that is, and I'm not sure it is desired behaviour.
I can change this back to applying as data, but I think for the future application as a shapekey is better behaviour, allowing the user more control.
More importantly, this fixes finalisation for Blender 2.90.

2020-09-08 22:20 UTC, calben commented
Working for other users here: https://github.com/animate1978/MB-Lab/issues/297

2020-09-11 10:18 UTC, metal3d commented
It could be cool to accept that in master branch please, to make us able to update to "master" from addons windows and use MB Lab in 2.90.

Anyone ?

2020-09-11 15:07 UTC, Prototype-Zer0 commented
I fixed line 1069 on my own last night but I also noticed an issue with the hair assets as it keeps running into the same bug, I will post the error message when I get home.

2020-09-16 19:07 UTC, metal3d commented
I also did it, worked for me. I prefer create hair my self afterward :) 

BTW: very impressive add-on, thanks to the authors

2020-09-24 00:49 UTC, FedoraGameDev commented
I added this fix in my setup and am receiving the same error as before the change.

`TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized`

2020-10-23 04:12 UTC, pupnsuds commented
I fixed this locally with modifier_apply instead of modifier_apply_as_shapekey. 

I haven’t dove into the he documentation for 2.9 but I believe modifier_apply will be have the same as “DATA” did previously. I could be mistaken

2020-10-23 04:17 UTC, calben commented
@pupnsuds you are correct 😄 
I changed the behaviour to match what I think is better behaviour more in line with how much of the rest of MBLab and to provide more flexibility.
I may revisit this decision when I go back to fix other errors that I totally forgot to fix in one of the other issue threads.

2020-11-14 05:20 UTC, LaikaN57 requested changes

2020-11-14 05:20 UTC, LaikaN57 commented on algorithms.py
> +            bpy.ops.object.modifier_apply_as_shapekey(modifier=modifier_name)
Use `modifier_apply`. https://docs.blender.org/api/current/bpy.ops.object.html#bpy.ops.object.modifier_apply

2020-12-13 13:24 UTC, animate1978 commented on algorithms.py
> +            bpy.ops.object.modifier_apply_as_shapekey(modifier=modifier_name)
Will be applying this merge soon

2020-12-22 05:15 UTC, animate1978 commented
This has been fixed with another pull request

2020-12-22 05:15 UTC, closed without merging